---
- name: "delete PPEAgent namespace"
  kubernetes.core.k8s:
    kind: "Namespace"
    api_version: "v1"
    name: "{{ ppeagentdeployment_namespace }}"
    state: "absent" 
    kubeconfig: "{{ ppeagentdeployment_kubeconfig }}"
    wait: yes
