---
- name: "install PPEAgent"
  hosts: "ppeagent"
  any_errors_fatal: yes
  connection: local
  tasks:
    - include_role: { name: "deploy", tasks_from: "apply" }
      vars:
        ppeagentdeployment_deploy_target_state: "present"
