---
- name: "install PPEAgent"
  hosts: "ppeagent"
  any_errors_fatal: yes
  connection: local
  tasks:
    - include_role: { name: "service", tasks_from: "apply" }
      vars:
        ppeagentdeployment_service_target_state: "absent"
