apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-ppe-credentials"
data:
    PPE_AGENT_EMAIL: {{ .Values.ppeCredentials.username | b64enc }}
    PPE_AGENT_PASSWORD: {{ .Values.ppeCredentials.password | b64enc }}
