---
- name: "perform PPEAgent deployment"
  block:
    - name: "create PPEAgent Helm Chart values file from template"
      ansible.builtin.template:
        src: "ppeagent-values.yaml.j2"
        dest: "{{ _ppeagent_values_file }}"
        mode: "0644"
      when: ppeagent_target_state == 'present'

    - name: "create PPEAgent namespace"
      kubernetes.core.k8s:
        kind: "Namespace"
        api_version: "v1"
        name: "{{ ppeagent_namespace }}"
        state: "present"
        kubeconfig: "{{ ppeagent_kubeconfig }}"
      when: ppeagent_target_state == 'present'

    - name: "{{ (ppeagent_target_state == 'present') | ternary('install', 'uninstall') }} PPEAgent Helm Chart"
      kubernetes.core.helm:
        state: "{{ ppeagent_target_state }}"
        kubeconfig: "{{ ppeagent_kubeconfig }}"
        release_name: "{{ _ppeagent_release_name }}"
        chart_ref: "{{ _ppeagent_chart_ref }}"
        release_namespace: "{{ ppeagent_namespace }}"
        values_files: "{{ _ppeagent_values_file }}"

    - name: "delete PPEAgent namespace"
      kubernetes.core.k8s:
        kind: "Namespace"
        api_version: "v1"
        name: "{{ ppeagent_namespace }}"
        state: "{{ ppeagent_target_state }}"
        kubeconfig: "{{ ppeagent_kubeconfig }}"
      when: ppeagent_target_state == 'absent'
  rescue:
    - name: "delete PPEAgent namespace"
      kubernetes.core.k8s:
        kind: "Namespace"
        api_version: "v1"
        name: "{{ ppeagent_namespace }}"
        state: "absent"
        kubeconfig: "{{ ppeagent_kubeconfig }}"
      when: ppeagent_target_state == 'present'
    - name: "cancel the playbook run"
      ansible.builtin.fail:
        msg: "PPEAgent deployment failed"
  always:
    - name: "remove PPEAgent Helm Chart values file"
      ansible.builtin.file:
        path: "{{ _ppeagent_values_file }}"
        state: "absent"
      ignore_errors: true
