{{- if eq .Values.ingress.enabled "yes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range .Values.ingress.annotations | default list }}
    {{ .key }}: {{ .value | quote }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - http:
      paths:
        {{- range .Values.ingress.routes | default list }}
        - path: {{ .path }}
          {{- if .pathType }}
          pathType: {{ .pathType }}
          {{- else }}
          pathType: Prefix
          {{- end }}
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
        {{- end }}
{{- end }}
{{- if .Values.ingress.tls -}}
  tls:
  - hosts:
    {{- range .Values.ingress.tls.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
{{- end }}
