{{- if eq .Values.ingress.enabled "yes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $annotation := .Values.ingress.annotations }}
    {{ $annotation.key }}: {{ $annotation.value | quote }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  - http:
      paths:
        {{- range $route := .Values.ingress.routes }}
        - path: {{ $route.path }}
          {{- if $route.pathType }}
          pathType: {{ $route.pathType }}
          {{- else }}
          pathType: Prefix
          {{- end }}
          backend:
            service:
              name: {{ $route.serviceName }}
              port:
                number: {{ $route.servicePort }}
        {{- end }}
{{- end }}

{{- if eq .Values.ingress.tls.enabled "yes" }}

tls:
  - hosts:
    {{- range $host := .Values.ingress.tls.hosts }}
    - {{ $host | quote }}
    {{- end }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}

{{- end }}
